name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  windows-vs2022:
    name: Windows VS2022
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 10.0.19041.0
          toolset: 14.30
      - name: Configure
        run: setup_vs2022.bat
        shell: cmd
      - name: Build
        run: msbuild.exe build\windows-vs2022\Falcor.sln /p:Configuration=${{ matrix.config }}
        shell: cmd
  windows-ninja-msvc:
    name: Windows Ninja/MSVC
    runs-on: windows-latest
    env:
      CMAKE_EXE: tools\.packman\cmake\bin\cmake.exe
      CMAKE_BUILD_PRESET: windows-ninja-msvc
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 10.0.19041.0
          toolset: 14.30
      - name: Configure
        run: setup.bat
        shell: cmd
      - name: Build
        run: |
          %CMAKE_EXE% --preset %CMAKE_BUILD_PRESET%
          %CMAKE_EXE% --build build/%CMAKE_BUILD_PRESET% --config ${{ matrix.config }}
        shell: cmd
  linux-gcc:
    name: Linux/GCC
    runs-on: ubuntu-22.04
    env:
      CMAKE_EXE: ./tools/.packman/cmake/bin/cmake
      CMAKE_BUILD_PRESET: linux-gcc
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup system dependencies
        run: sudo apt install -y xorg-dev libgtk-3-dev
        shell: bash
      - name: Configure
        run: ./setup.sh
        shell: bash
      - name: Build
        run: |
          ${CMAKE_EXE} --preset ${CMAKE_BUILD_PRESET}
          ${CMAKE_EXE} --build build/${CMAKE_BUILD_PRESET} --config ${{ matrix.config }}
        shell: bash
