name: compile

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  windows:
    name: Windows/MSVC
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup
        run: setup.bat
