name: compile

on:
  pull_request:
    branches: ["master"]

jobs:
  windows:
    name: Windows Ninja/MSVC
    runs-on: windows-latest
    env:
      CMAKE_EXE: tools\.packman\cmake\bin\cmake.exe
      CMAKE_BUILD_PRESET: windows-ninja-msvc
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup
        run: setup.bat
        shell: cmd
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 10.0.19041.0
          toolset: 14.30
      - name: Build
        run: |
          %CMAKE_EXE% --preset %CMAKE_BUILD_PRESET%
          %CMAKE_EXE% --build build/%CMAKE_BUILD_PRESET% --config ${{ matrix.config }}
        shell: cmd
  linux:
    name: Linux/GCC
    runs-on: ubuntu-22.04
    env:
      CMAKE_EXE: ./tools/.packman/cmake/bin/cmake
      CMAKE_BUILD_PRESET: linux-gcc
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install system dependencies
        run: sudo apt install -y xorg-dev libgtk-3-dev
        shell: bash
      - name: Setup
        run: ./setup.sh
        shell: bash
      - name: Build
        run: |
          ${CMAKE_EXE} --preset ${CMAKE_BUILD_PRESET}
          ${CMAKE_EXE} --build build/${CMAKE_BUILD_PRESET} --config ${{ matrix.config }}
        shell: bash
